apiVersion: v1
kind: Service
metadata:
  name: {{ include "booth-streamlit.fullname" . }}
  labels:
    {{- include "booth-streamlit.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "booth-streamlit.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
    {{- if .Values.dataAccess.enabled }}
    - name: internal
      port: 8081
      targetPort: internal
    {{- end }}
