{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "booth-streamlit.serviceAccountName" . }}
  labels:
    {{- include "booth-streamlit.labels" . | nindent 4 }}
{{- end }}
